Checklist 1st view
knn90/DaiQiOS pull request #1
Opened 2023-09-08 08:05 UTC by vietanh253

2023-09-08 08:26 UTC, knn90 requested changes

2023-09-08 08:26 UTC, knn90 commented on DaiQiOS/DaiQiOS/Todaychecklist.swift
> +}
Please move ChecklistItem to separate file

2023-09-08 08:26 UTC, knn90 commented on DaiQiOS/DaiQiOS/Todaychecklist.swift
> +}
ContainerView should be a subview of Todaychecklist. 
Like:
`TodayCheckList {
    Container{
         ZStack
    }
}`

2023-09-08 08:26 UTC, knn90 commented on DaiQiOS/DaiQiOS/Todaychecklist.swift
> +    }
The Preview should be a separate struct

2023-09-08 08:26 UTC, knn90 commented on DaiQiOS/DaiQiOS/Todaychecklist.swift
> +struct Todaychecklist: View {
Naming convention: TodayChecklist

2023-09-08 09:26 UTC, knn90 requested changes

2023-09-08 09:26 UTC, knn90 commented on DaiQiOS/DaiQiOS/Todaychecklist.swift
> +            //            Color.white.edgesIgnoringSafeArea(.all)
Please remove commented code

2023-09-08 09:26 UTC, knn90 commented on DaiQiOS/DaiQiOS/Todaychecklist.swift
> +                }
Please use @ViewBuilder to extract this button with name `addTaskButton`

2023-09-08 09:26 UTC, knn90 commented on DaiQiOS/DaiQiOS/Todaychecklist.swift
> +                        }
Create a new view for example `TaskCell`  to make the `TodayChecklist` shorter

2023-09-08 09:26 UTC, knn90 commented on DaiQiOS/DaiQiOS/Todaychecklist.swift
> +                        .bold()
Make this a navigationBarTitle instead of a Text

2023-09-08 09:26 UTC, knn90 commented on DaiQiOS/DaiQiOS/Todaychecklist.swift
> +                    .frame(alignment: .center)
We can remove this

2023-09-11 03:10 UTC, vietanh253 commented on DaiQiOS/DaiQiOS/Todaychecklist.swift
> +                        .bold()
navigationBarTitle is deprecated

2023-09-11 04:15 UTC, knn90 requested changes

2023-09-11 04:15 UTC, knn90 commented on DaiQiOS/DaiQiOS/TaskCell.swift
> +        ForEach(checklistItems.indices, id: \.self) { index in
Move ForEach to the List

2023-09-11 04:15 UTC, knn90 commented on DaiQiOS/DaiQiOS/Todaychecklist.swift
> +    }
Fix indentation

2023-09-11 04:15 UTC, knn90 commented on DaiQiOS/DaiQiOS/Todaychecklist.swift
> +                            List {
Fix indentation

2023-09-11 09:44 UTC, knn90 approved these changes

2023-09-11 09:45 UTC, merged